first attempt pymongo lamda to extract civ stats
erin-fitzpatric/aom-lambda pull request #1
Opened 2024-09-13 00:37 UTC by jdduprey

2024-09-13 01:10 UTC, erin-fitzpatric requested changes

2024-09-13 01:10 UTC, erin-fitzpatric commented on extract-stats/civs_stats.py
> +    }, {
These two $match opperations should be able to be combined into one.

2024-09-13 01:10 UTC, erin-fitzpatric commented on extract-stats/civs_stats.py
> +        '$addFields': {
Can these multiple $addFields be combined?

2024-09-13 23:07 UTC, jdduprey commented on extract-stats/civs_stats.py
> +    }, {
done

2024-09-13 23:12 UTC, jdduprey commented on extract-stats/civs_stats.py
> +        '$addFields': {
Not as is. These stages are a bit hacky but the only way I could figure out in MQL syntax to get the opponents civ into a playes match record. I couldn't figure out how to assign array[0]["civ_id"] to array[1]["civ_id"] so I converted them to individual fields...

2024-09-14 06:07 UTC, erin-fitzpatric approved these changes

2024-09-14 06:07 UTC, merged